FROM rasa/rasa-sdk:3.6.2

COPY . /dinhgiaxe-ai-assistant/actions

WORKDIR /dinhgiaxe-ai-assistant

# Optional: install extra dependencies if needed
# COPY requirements-actions.txt . 
# RUN pip install -r requirements-actions.txt

# CMD ["rasa", "run", "actions"]
